language: node_js
node_js:
  - "10.16.0"

install:
- cd server
- npm install
- cd ..
- cd client
- npm install -g firebase-tools

script:
- npx cypress open

after_success: 
- firebase deploy --token $FIREBASE_TOKEN