language: node_js
node_js:
  - "10.16.0"

install:
- cd server
- npm install
- cd ..
- cd client
- npm install -g firebase-tools
- cd ..

script:
- cd server
- npm start
- cd ..
- cd client
- npm start
- npx cypress run

after_success: 
- firebase deploy --token $FIREBASE_TOKEN